import React from "react";
import FileOfRow from "./FileOfRow";
import WorkDays from "./WorkDays";

export const usersData = [
  {
    id: "1",
    name: "عبدالرحيم السيد عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [1, 3, 5, 6],
    file: "",
    settings: "",
  },
  {
    id: "2",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [1, 2, 3, 5, 6],
    file: "",
    settings: "",
  },
  {
    id: "3",
    name: "طارق السيد عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "4",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "5",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "6",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "7",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "8",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "9",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "10",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "11",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "12",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "13",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "14",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "15",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "16",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
  {
    id: "17",
    name: "عبدالرحيم صقر",
    email: "abdulrahimsakr01@gmailcom",
    workDays: [2, 3, 6],
    file: "",
    settings: "",
  },
];
// ===================================================================================
export const columnsData = [
  {
    id: 5,
    flexGrow: 1,
    label: "الملفات",
    dataKey: "file",
  },
  {
    id: 4,
    flexGrow: 1,
    label: "أيام العمل",
    dataKey: "workDays",
  },
  {
    id: 3,
    flexGrow: 1.5,
    label: "البريد الإلكتروني",
    dataKey: "email",
  },
  {
    id: 2,
    flexGrow: 1,
    label: "الإسم بالكامل",
    dataKey: "name",
  },
  {
    id: 1,
    flexGrow: 0.5,
    label: "id رقم ال",
    dataKey: "id",
  },
];
